'use strict';
const C=window.SeansCore, $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=x=>/^https:\/\//i.test(String(x||''))?String(x):'';
const STORE='seans.prototype.v1';
function read(key,fallback,session=false){try{const store=session?window.sessionStorage:window.localStorage;return JSON.parse(store.getItem(STORE+'.'+key))??fallback;}catch{return fallback;}}
function write(key,value,session=false){try{const store=session?window.sessionStorage:window.localStorage;store.setItem(STORE+'.'+key,JSON.stringify(value));}catch{}}
let options=read('options',{services:[],rounds:25,genre:'',runtime:'',rating:'',year:''});
let seen=read('seen',[]), saved=read('saved',[]), catalogue=null, activeMovies=new Map(), game=null, history=[], screen='loading', error='', offlineCopy=false, pending=0, toastTimer;
let gameFetchedAt=null;
const genreNames={act:'Akcja i przygoda',ani:'Animacja',cmy:'Komedia',crm:'Kryminał',doc:'Dokumentalny',drm:'Dramat',eur:'Kino europejskie',fml:'Familijny',fnt:'Fantasy',hrr:'Horror',hst:'Historyczny',msc:'Muzyczny',rma:'Romans',scf:'Science fiction',spt:'Sportowy',trl:'Thriller',war:'Wojenny',wsn:'Western'};
const genreName=g=>genreNames[g.id]||g.name;
function currentDate(){return game?(gameFetchedAt||catalogue.fetchedAt):catalogue?.fetchedAt;}
let resume=read('session',null,true);
const pretty={netflix:'NETFLIX',prime:'prime video',disney:'Disney+',max:'HBO Max',apple:'Apple TV',sky:'SkyShowtime'};
function dateText(value){const d=new Date(value);return Number.isFinite(d.getTime())?d.toLocaleString('pl-PL',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'brak daty';}
function ageHours(){return catalogue?(Date.now()-new Date(currentDate()).getTime())/3600000:Infinity;}
function isStale(){return offlineCopy||ageHours()>3;}
function notify(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function movie(id){return activeMovies.get(id)||catalogue?.movies.find(m=>m.id===id)||saved.find(m=>m.id===id);}
function selectedOffers(m){return(m?.offers||[]).filter(o=>options.services.includes(o.provider));}
function tags(m){return selectedOffers(m).map(o=>`<span class="provider-tag">${esc(o.name)}</span>`).join('');}
function meta(m){return[m.year,m.runtime?`${m.runtime} min`:null,m.rating?`★ ${Number(m.rating).toFixed(1)} IMDb`:null].filter(Boolean).join(' · ');}
function image(m,cls='poster'){const u=safeURL(m.poster);return u?`<img class="${cls}" src="${esc(u)}" alt="Plakat: ${esc(m.title)}" loading="eager" decoding="async" referrerpolicy="no-referrer">`:'';}
function poster(m,badge=''){return`<div class="poster-wrap"><span class="poster-fallback">${esc(m.title)}</span>${image(m)}${badge}</div>`;}
function currentPool(){return catalogue?C.filterMovies(catalogue.movies,options,seen):[];}
function statusHTML(){if(!catalogue)return'';return`<div class="status ${isStale()?'stale':''}"><span class="dot"></span><div>${offlineCopy?'Nie udało się pobrać nowej kopii. ':''}${ageHours()>3?'Dane mogą być nieaktualne. ':''}Oferty PL sprawdzone ${dateText(currentDate())}.<br>${catalogue.movies.length} filmów w puli · odświeżanie zaplanowane co godzinę.</div></div>`;}
function footer(){return`<span>Wybieraj filmy, nie kolejne menu.</span><span>Dostępność: <a href="https://www.justwatch.com/pl" target="_blank" rel="noopener noreferrer">JustWatch</a> · Polska</span>`;}
function saveOptions(){write('options',options);}
function persist(){if(!game)return;write('session',{game,options,pool:[...activeMovies.values()],fetchedAt:currentDate()},true);resume=read('session',null,true);}
function remember(){history.push({game:C.clone(game),seen:seen.slice()});if(history.length>100)history.shift();}
function draw(){const views={home:homeHTML,duel:duelHTML,winner:winnerHTML,library:libraryHTML,loading:()=>`<div class="loader"><div class="spinner"></div><h2>Szukamy czegoś na wieczór.</h2><p>Pobieram katalog filmów dostępnych w polskich abonamentach.</p></div>`,error:errorHTML};$('#app').innerHTML=(views[screen]||homeHTML)();$('#footer').innerHTML=footer();document.querySelectorAll('img.poster').forEach(img=>img.addEventListener('error',()=>img.remove(),{once:true}));}
function homeHTML(){const pool=currentPool();const genres=new Map();catalogue.movies.forEach(m=>m.genres.forEach(g=>genres.set(g.id,genreName(g))));const select=(id,label,items)=>`<label class="field"><span>${label}</span><select data-option="${id}" aria-label="${label}">${items.map(([value,name])=>`<option value="${esc(value)}" ${String(options[id])===String(value)?'selected':''}>${esc(name)}</option>`).join('')}</select></label>`;return`<div class="home-layout"><section class="hero"><div class="eyebrow"><span class="dot"></span>WIECZÓR BEZ PRZEWIJANIA</div><h1>Mniej szukania.<br><span>Więcej oglądania.</span></h1><p>Dwa filmy. Jeden wybór. Zwycięzca zostaje, a Ty coraz lepiej wiesz, na co masz dziś ochotę.</p>${statusHTML()}${resume?.game&&!game?`<button class="secondary" style="margin-top:20px" data-action="resume">↶ Wznów ostatni wybór</button>`:''}</section><section><div class="section-label">Gdzie oglądasz?<small>Wybierz swoje abonamenty</small></div><div class="service-grid">${catalogue.providers.map(p=>{const n=catalogue.movies.filter(m=>m.offers.some(o=>o.provider===p.id)).length;return`<button class="service" data-service="${esc(p.id)}" aria-pressed="${options.services.includes(p.id)}" aria-label="${esc(p.name)}"><span class="check">✓</span><strong>${esc(pretty[p.id]||p.name)}</strong><small>${n} filmów w puli</small></button>`;}).join('')}</div><div class="filter-grid">${select('genre','Dzisiejszy klimat',[['','Każdy gatunek'],...[...genres.entries()].sort((a,b)=>a[1].localeCompare(b[1],'pl'))])}${select('runtime','Ile masz czasu?',[['','Bez limitu'],[100,'Do 100 minut'],[120,'Do 2 godzin'],[150,'Do 2,5 godziny']])}${select('rating','Ocena IMDb',[['','Każda ocena'],[6,'Co najmniej 6,0'],[7,'Co najmniej 7,0'],[8,'Co najmniej 8,0']])}${select('year','Rok premiery',[['','Wszystkie lata'],[2000,'Od 2000 roku'],[2010,'Od 2010 roku'],[2020,'Od 2020 roku']])}</div><div class="section-label">Ile pojedynków?<small>Możesz skończyć wcześniej</small></div><div class="segments">${[10,25,50].map(n=>`<button class="segment" data-rounds="${n}" aria-pressed="${Number(options.rounds)===n}">${n}</button>`).join('')}</div><div class="start-wrap"><button class="primary" data-action="start" ${pool.length<2?'disabled':''}>${!options.services.length?'Zaznacz swoje platformy':pool.length<2?'Za mało filmów — zmień filtry':'Znajdźmy film'} <span class="arrow">↗</span></button><p class="help-line">${options.services.length?`${pool.length} pasujących filmów · `:''}Bez konta. Bez wypożyczania. Tylko abonamenty.</p>${seen.length?`<button class="text-btn" data-action="clear-seen">Przywróć obejrzane (${seen.length})</button>`:''}</div></section></div>`;}
function cardHTML(id,side){const m=movie(id);if(!m)return'';const champion=game.champion===id;const badges=`<div class="poster-badge">${champion?'<span class="badge champ">✦ TWÓJ FAWORYT</span>':'<span></span>'}${m.rating?`<span class="badge rating">★ ${Number(m.rating).toFixed(1)}</span>`:''}</div>`;return`<article class="movie" data-movie="${esc(id)}"><button class="poster-button" data-pick="${side}" aria-label="Wybieram: ${esc(m.title)}">${poster(m,badges)}</button><h2>${esc(m.title)}</h2><div class="movie-meta">${esc([m.year,m.runtime?m.runtime+' min':null].filter(Boolean).join(' · '))}<br>${esc(m.genres.slice(0,2).map(g=>genreName(g)).join(' / '))}</div><div class="provider-tags">${tags(m)}</div><button class="primary pick" data-pick="${side}">Ten wybieram <span>↗</span></button><div class="movie-tools"><button class="text-btn" data-seen="${side}">✓ Widziałem/am</button><button class="text-btn" data-detail="${esc(id)}">Opis ⓘ</button></div></article>`;}
function duelHTML(){return`<div class="duel-top"><span>TWÓJ FILM NA DZIŚ</span><span><strong>${Math.min(game.completed+1,game.goal)}</strong> / ${game.goal} pojedynków</span></div><div class="progress"><div style="width:${Math.round(game.completed/game.goal*100)}%"></div></div><div class="duel-title"><h1>Na który masz ochotę?</h1><p>${game.champion?'Twój faworyt zostaje. Nowy film musi go pokonać.':'Kliknij plakat lub przycisk. Wybierz intuicyjnie.'}</p></div><div class="duel">${cardHTML(game.pair[0],0)}<span class="versus">VS</span>${cardHTML(game.pair[1],1)}</div><div class="duel-actions"><button class="text-btn" data-action="undo" ${history.length?'':'disabled'}>↶ Cofnij</button><button class="text-btn" data-action="skip">Żaden z nich</button><button class="secondary finish" data-action="finish" ${game.champion?'':'disabled'}>Mam film ✓</button></div><div class="duel-end">${isStale()?statusHTML():''}<p class="help-line">${Math.max(0,game.deck.length-game.cursor)} nowych przeciwników w tej puli · <button class="text-btn" data-action="home">Zmień ustawienia</button></p></div>`;}
function winnerHTML(){const m=movie(game?.champion);if(!m)return`<div class="error-box"><h2>Przejrzeliśmy tę pulę.</h2><p>Nie został żaden kandydat. Zmień filtry lub platformy i spróbuj z nową pulą.</p><button class="primary" data-action="home">Zmień ustawienia</button></div>`;const offers=selectedOffers(m);return`<section class="winner"><div class="eyebrow" style="justify-content:center">✦ KONIEC SZUKANIA</div><h1>Dziś oglądasz.</h1><p class="winner-intro">${game.completed} ${game.completed===1?'wybór':'wyborów'} później — oto Twój film.</p>${poster(m)}<h2>${esc(m.title)}</h2><div class="movie-meta">${esc(meta(m))}</div><div class="provider-tags">${tags(m)}</div><p class="summary">${esc(m.description||'Opis tego filmu nie jest dostępny w źródle.')}</p>${isStale()?`<div class="notice">Dane z ${dateText(currentDate())}. Sprawdź dostępność przed seansem.</div>`:''}<div class="watch-links">${offers.map(o=>`<a class="primary" href="${esc(safeURL(o.url))}" target="_blank" rel="noopener noreferrer">▶ Otwórz ${esc(o.name)} <span>↗</span></a>`).join('')}</div><p class="help-line">Oferta w abonamencie według danych z ${dateText(currentDate())}.<br>Platforma może poprosić o zalogowanie. Dostępność nie jest gwarantowana.</p><div class="winner-actions"><button class="secondary" data-action="save">${saved.some(s=>s.id===m.id)?'♥ Zapisany':'♡ Zapisz na później'}</button><button class="secondary" data-action="more" ${game.pair.every(Boolean)?'':'disabled'}>Jeszcze 10 par</button></div><div class="winner-bottom"><a class="inline-link" href="${esc(safeURL(m.url))}" target="_blank" rel="noopener noreferrer">Sprawdź w JustWatch ↗</a><button class="text-btn" data-action="home">Wybierz od nowa</button></div></section>`;}
function libraryHTML(){return`<section class="library"><div class="eyebrow">TWOJA LISTA</div><h1>Na kolejny wieczór.</h1><p class="help-line" style="text-align:left">Zapisane tylko w tej przeglądarce. ${seen.length} oznaczonych jako obejrzane.</p>${saved.length?saved.map(m=>`<div class="library-row">${image(m,'library-poster')}<div class="info"><h3>${esc(m.title)}</h3><p>${esc(meta(m))}</p><a class="inline-link" href="${esc(safeURL(m.url))}" target="_blank" rel="noopener noreferrer">Aktualna dostępność ↗</a></div><button class="text-btn" data-remove="${esc(m.id)}">Usuń</button></div>`).join(''):'<div class="error-box"><p>Tu trafią filmy zapisane po finale pojedynków.</p></div>'}<button class="primary" style="margin-top:23px" data-action="home">Wróć do wybierania</button></section>`;}
function errorHTML(){return`<div class="error-box"><div class="eyebrow">POŁĄCZENIE Z KATALOGIEM</div><h2>Nie udało się pobrać filmów.</h2><p>${esc(error||'Sprawdź połączenie z internetem i spróbuj ponownie.')}</p><p>Nie pokazuję wymyślonej listy ani filmów z innego kraju.</p><button class="primary" data-action="reload">Spróbuj ponownie ↻</button></div>`;}
async function getJSON(url){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(url,{signal:controller.signal,cache:'no-store',credentials:'omit'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json();}finally{clearTimeout(timer);}}
function validCatalogue(c){return c?.version===1&&c.country==='PL'&&c.monetization==='FLATRATE'&&Array.isArray(c.providers)&&c.providers.length>0&&Array.isArray(c.movies)&&c.movies.length>=2&&Number.isFinite(Date.parse(c.fetchedAt))&&c.movies.every(m=>typeof m.id==='string'&&typeof m.title==='string'&&Array.isArray(m.genres)&&Array.isArray(m.offers)&&m.offers.length>0&&m.url?.startsWith('https://www.justwatch.com/pl/'));}
async function load(){screen='loading';draw();offlineCopy=false;const endpoints=['https://raw.githubusercontent.com/KADARstudio/WycenaSesji/film-duel-prototype/film-duel/catalog.json'];if(location.protocol.startsWith('http'))endpoints.push(new URL('catalog.json',location.href).href);let data;for(const url of endpoints){try{const c=await getJSON(url);if(validCatalogue(c)){data=c;break;}}catch(e){console.warn('Catalogue unavailable',url,e.message);}}if(!data&&window.SEANS_SEED&&validCatalogue(window.SEANS_SEED)){data=window.SEANS_SEED;offlineCopy=true;}if(!data){const c=read('catalogue',null);if(validCatalogue(c)){data=c;offlineCopy=true;}}if(!data){screen='error';error='Źródło danych lub połączenie jest chwilowo niedostępne. Ten prototyp wymaga internetu przy pierwszym uruchomieniu.';draw();return;}catalogue=data;write('catalogue',data);options.services=options.services.filter(id=>data.providers.some(p=>p.id===id));screen='home';draw();}
function afterMove(){screen=game.done?'winner':'duel';persist();draw();}
function start(){const pool=currentPool();if(pool.length<2)return;activeMovies=new Map(pool.map(m=>[m.id,m]));gameFetchedAt=catalogue.fetchedAt;game=C.createGame(C.shuffle(pool),Number(options.rounds));history=[];afterMove();window.scrollTo(0,0);if(pool.length<=options.rounds)notify(`W tej puli będzie ${game.goal} pojedynków.`);}
function showDetail(id){const m=movie(id);if(!m)return;$('#sheet-content').innerHTML=`${image(m,'detail-poster')}<h2>${esc(m.title)}</h2><p>${esc(meta(m))}</p><div class="provider-tags">${tags(m)}</div><p class="description">${esc(m.description||'Brak opisu w bazie.')}</p><div class="source-block"><a class="inline-link" href="${esc(safeURL(m.url))}" target="_blank" rel="noopener noreferrer">Film w JustWatch ↗</a><p class="small">Oferty PL sprawdzone ${dateText(currentDate())}. Ocena pochodzi z IMDb, przekazana przez JustWatch.</p></div>`;$('#sheet').showModal();}
function about(){const detail=catalogue?`${catalogue.movies.length} filmów; pobrano ${dateText(currentDate())}.`:'Katalog nie został jeszcze pobrany.';$('#sheet-content').innerHTML=`<div class="eyebrow">SEANS · WERSJA 0.1</div><h2>Dwa filmy.<br>Jeden wieczór.</h2><p>W każdym pojedynku wybrany film zostaje po tej samej stronie. Zmieniamy wyłącznie przeciwnika. To prosty turniej, nie model AI i nie obietnica idealnej rekomendacji.</p><h3>Skąd są filmy?</h3><p>Źródło: <a href="https://www.justwatch.com/pl" target="_blank" rel="noopener noreferrer">JustWatch</a>. Pobieramy próbkę do 100 popularnych filmów na platformę i sprawdzamy polskie oferty w abonamencie. Nie pobieramy całych katalogów. Pomijamy wypożyczanie, zakup oraz dodatkowe kanały Amazon.</p><p>${esc(detail)} Odświeżanie serwerowe jest zaplanowane co godzinę; może się opóźnić lub nie udać. Data pokazuje ostatnie udane pobranie, nie gwarancję dostępności w chwili odtwarzania.</p><h3>To prototyp, nie partner JustWatch</h3><p>Integracja jest nieoficjalna, do prywatnego testu bez monetyzacji. Przed publikacją komercyjną trzeba uzgodnić licencję danych i przejść na wspierany interfejs. Plakaty i znaki należą do ich właścicieli.</p><h3>Prywatność</h3><p>Nie ma logowania, reklam ani naszej analityki. Twoje ustawienia, obejrzane filmy i lista zapisują się lokalnie w przeglądarce. Hosting i serwery plakatów otrzymują zwykłe żądania sieciowe, w tym adres IP. Nie łączymy się z kontami Netflix ani innych platform.</p><h3>Na ekranie telefonu</h3><p>Otwórz stronę w Safari, wybierz Udostępnij, a potem „Do ekranu głównego”. To aplikacja przeglądarkowa, nie instalacja z App Store.</p><button class="secondary danger" data-action="clear-data">Usuń moje lokalne dane</button>`;$('#sheet').showModal();}
document.addEventListener('change',e=>{const key=e.target.dataset.option;if(key){options[key]=e.target.value;saveOptions();draw();}});
document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;const d=el.dataset;
 if(d.service){options.services=options.services.includes(d.service)?options.services.filter(s=>s!==d.service):[...options.services,d.service];saveOptions();draw();return;}
 if(d.rounds){options.rounds=Number(d.rounds);saveOptions();draw();return;}
 if(d.pick!==undefined){if(screen!=='duel'||Date.now()<pending)return;pending=Date.now()+240;remember();game=C.choose(game,Number(d.pick));afterMove();return;}
 if(d.seen!==undefined){if(screen!=='duel')return;remember();const side=Number(d.seen),id=game.pair[side];if(!seen.includes(id))seen.push(id);write('seen',seen);game=C.replace(game,side);afterMove();notify('Film pominięty i oznaczony jako obejrzany.');return;}
 if(d.detail){showDetail(d.detail);return;}
 if(d.remove){saved=saved.filter(m=>m.id!==d.remove);write('saved',saved);draw();return;}
 switch(d.action){
 case'home':screen=catalogue?'home':'error';game=null;draw();window.scrollTo(0,0);break;
 case'start':start();break;
 case'undo':if(history.length){const h=history.pop();game=h.game;seen=h.seen;write('seen',seen);pending=0;afterMove();}break;
 case'skip':if(game&&!game.done){remember();game=C.skipBoth(game);afterMove();}break;
 case'finish':if(game?.champion){remember();game.done=true;afterMove();window.scrollTo(0,0);}break;
 case'more':if(game){game=C.continueGame(game);afterMove();window.scrollTo(0,0);}break;
 case'save':{const m=movie(game?.champion);if(m&&!saved.some(s=>s.id===m.id)){saved.unshift(m);write('saved',saved);draw();notify('Zapisano na kolejny wieczór.');}break;}
 case'library':screen='library';draw();break;
 case'about':about();break;
 case'close':$('#sheet').close();break;
 case'reload':load();break;
 case'clear-seen':if(confirm('Przywrócić wszystkie obejrzane filmy do losowania?')){seen=[];write('seen',seen);draw();}break;
 case'clear-data':if(confirm('Usunąć ustawienia, obejrzane i zapisane filmy z tej przeglądarki?')){seen=[];saved=[];options={services:[],rounds:25,genre:'',runtime:'',rating:'',year:''};write('seen',seen);write('saved',saved);saveOptions();write('session',null,true);resume=null;game=null;history=[];$('#sheet').close();screen='home';draw();notify('Lokalne dane usunięte.');}break;
 case'resume':if(resume?.pool?.length>=2){activeMovies=new Map(resume.pool.map(m=>[m.id,m]));game=resume.game;options=resume.options;history=[];gameFetchedAt=resume.fetchedAt;afterMove();notify('Wznowiono wybór z poprzedniej puli filmów.');}break;
 }
});
$('#sheet').addEventListener('click',e=>{if(e.target===$('#sheet')){const r=$('#sheet').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#sheet').close();}});
load();
